import type { Project, Position, Activity, Quest, Proposal } from '@/types';

// Using functions that compute dates at import time
const now = Date.now();
const d = 86400000;
const h = 3600000;

export const PROJECTS: Project[] = [
  {
    id: 'zetta-chain', name: 'ZETTA CHAIN', symbol: 'ZETTA', logo: '/assets/projects/zetta-chain.svg',
    description: 'Layer 1 blockchain designed for the ZETTA ecosystem. Sub-second finality, EVM compatibility, and native crypto-fiat rails built for mass adoption.',
    chain: 'zetta', chainName: 'ZettaChain',
    saleType: 'Fair Launch', saleTypeKey: 'fairlaunch',
    status: 'live', featured: true,
    rate: '1 BNB = 125,000 ZETTA', ratePerBase: 125000,
    raised: 10562817, target: 12500000, softCap: 500000, liquidity: 70,
    participants: 2847,
    startsAt: now - 12 * d, endsAt: now + 4 * d + 7 * h,
    minBuy: 0.1, maxBuy: 10, kyc: true, audited: 'Cyberscope', refundable: true,
    aiScore: 94,
    aiBreakdown: { tokenomics: 96, contract: 98, team: 92, market: 90, liquidity: 95, community: 89 },
    aiSummary: 'ZETTA CHAIN demonstrates exceptional fundamentals across all vetting dimensions. Strong tokenomics with 70% liquidity lock, audited contract with zero critical issues, and a verified team.',
    aiStrengths: ['100-year LP lock', 'Cyberscope audited — 0 critical issues', 'Verified team with 4+ years on-chain history', 'Anti-bot protection', 'Multi-sig treasury'],
    aiFlags: [],
    tokenomics: { supply: '1,000,000,000', presale: 20, liquidity: 70, team: 5, marketing: 5 },
    vesting: 'TGE: 25% | 3 months linear',
  },
  {
    id: 'ai-oracle', name: 'AI Oracle', symbol: 'AIO', logo: '/assets/projects/ai-oracle.svg',
    description: 'Decentralized AI oracle network for smart contracts. Real-time GPT-class models on-chain.',
    chain: 'eth', chainName: 'Ethereum',
    saleType: 'Bonding Curve', saleTypeKey: 'bondingcurve',
    status: 'live', hot: true,
    rate: 'Dynamic (Bonding Curve)', ratePerBase: 28000,
    raised: 1200000, target: 3000000, softCap: 0, liquidity: 85,
    participants: 632,
    startsAt: now - d, endsAt: now + 9 * d,
    minBuy: 0.01, maxBuy: 100, kyc: true, audited: 'Trail of Bits', refundable: false,
    aiScore: 96,
    aiBreakdown: { tokenomics: 98, contract: 98, team: 96, market: 94, liquidity: 98, community: 90 },
    aiSummary: 'Top-tier AI infrastructure project. Trail of Bits audit, team from Anthropic and OpenAI. Bonding curve ensures fair launch.',
    aiStrengths: ['Trail of Bits audit (elite)', 'Team from Anthropic & OpenAI', 'Bonding curve (anti-bot)', '85% liquidity', 'Zero pre-mine'],
    aiFlags: [],
    tokenomics: { supply: '1,000,000,000', presale: 10, liquidity: 85, team: 3, marketing: 2 },
  },
  {
    id: 'pixelverse', name: 'PixelVerse', symbol: 'PIXV', logo: '/assets/projects/pixelverse.svg',
    description: 'Open-world Web3 MMORPG with player-owned economy. Built on custom gaming L2.',
    chain: 'polygon', chainName: 'Polygon',
    saleType: 'LBP', saleTypeKey: 'lbp',
    status: 'live', trending: true,
    rate: 'Dynamic (LBP)', ratePerBase: 0,
    raised: 3200000, target: 6000000, softCap: 1500000, liquidity: 70,
    participants: 1842,
    startsAt: now - 3 * d, endsAt: now + d + 6 * h,
    minBuy: 0.05, maxBuy: 20, kyc: true, audited: 'Cyberscope', refundable: false,
    aiScore: 89,
    aiBreakdown: { tokenomics: 90, contract: 92, team: 88, market: 86, liquidity: 88, community: 92 },
    aiSummary: 'Premium gaming project using Liquidity Bootstrapping Pool for fair price discovery. Strong community (150k+).',
    aiStrengths: ['LBP (anti-whale)', 'Team from Blizzard/Riot', 'Cyberscope audit', '150k+ Discord'],
    aiFlags: [],
    tokenomics: { supply: '1,500,000,000', presale: 15, liquidity: 70, team: 10, marketing: 5 },
  },
  {
    id: 'metavault', name: 'MetaVault Finance', symbol: 'MVT', logo: '/assets/projects/metavault.svg',
    description: 'Multi-chain yield aggregator with AI-powered strategy selection and automated rebalancing.',
    chain: 'bsc', chainName: 'BSC',
    saleType: 'Presale', saleTypeKey: 'presale',
    status: 'live', trending: true,
    rate: '1 BNB = 8,500 MVT', ratePerBase: 8500,
    raised: 2140000, target: 3000000, softCap: 500000, liquidity: 65,
    participants: 1254,
    startsAt: now - 8 * d, endsAt: now + 2 * d + 14 * h,
    minBuy: 0.05, maxBuy: 5, kyc: true, audited: 'CertiK', refundable: false,
    aiScore: 86,
    aiBreakdown: { tokenomics: 88, contract: 92, team: 82, market: 84, liquidity: 85, community: 86 },
    aiSummary: 'Strong multi-chain yield protocol with credible audit. Team has moderate on-chain history.',
    aiStrengths: ['CertiK audit', 'Clear tokenomics', 'Working product demo'],
    aiFlags: ['Some team members anonymous'],
    tokenomics: { supply: '500,000,000', presale: 25, liquidity: 60, team: 10, marketing: 5 },
  },
  {
    id: 'nexgen-ai', name: 'NexGen AI', symbol: 'NXAI', logo: '/assets/projects/nexgen-ai.svg',
    description: 'AI-powered on-chain analytics, trading signals, and autonomous agents.',
    chain: 'polygon', chainName: 'Polygon',
    saleType: 'Fair Launch', saleTypeKey: 'fairlaunch',
    status: 'upcoming', trending: true,
    rate: 'TBA', ratePerBase: 0,
    raised: 0, target: 5000000, softCap: 1000000, liquidity: 75,
    participants: 0,
    startsAt: now + 3 * d, endsAt: now + 12 * d,
    minBuy: 0.1, maxBuy: 20, kyc: true, audited: 'PeckShield', refundable: true,
    aiScore: 91,
    aiBreakdown: { tokenomics: 94, contract: 96, team: 92, market: 88, liquidity: 92, community: 84 },
    aiSummary: 'Exceptional AI project with PeckShield audit and verified team from Google AI and OpenAI backgrounds.',
    aiStrengths: ['Team from Google AI & OpenAI', 'PeckShield audit', 'Refundable (DYCO)', '75% liquidity'],
    aiFlags: ['Community still modest (<10k)'],
    tokenomics: { supply: '200,000,000', presale: 18, liquidity: 72, team: 8, marketing: 2 },
  },
  {
    id: 'zettabridge', name: 'ZettaBridge', symbol: 'ZBRG', logo: '/assets/projects/zettabridge.svg',
    description: 'Cross-chain bridge with sub-minute transfers across 20+ chains. Native to the ZETTA ecosystem.',
    chain: 'zetta', chainName: 'ZettaChain',
    saleType: 'Fair Launch', saleTypeKey: 'fairlaunch',
    status: 'upcoming', hot: true,
    rate: 'TBA', ratePerBase: 0,
    raised: 0, target: 4000000, softCap: 800000, liquidity: 80,
    participants: 0,
    startsAt: now + 7 * d, endsAt: now + 20 * d,
    minBuy: 0.1, maxBuy: 10, kyc: true, audited: 'Cyberscope', refundable: true,
    aiScore: 93,
    aiBreakdown: { tokenomics: 95, contract: 96, team: 92, market: 90, liquidity: 96, community: 88 },
    aiSummary: 'Premium project launching on ZETTA Chain with industry-leading 80% liquidity.',
    aiStrengths: ['80% liquidity (top-tier)', 'ZETTA ecosystem integration', 'Refundable (DYCO)'],
    aiFlags: [],
    tokenomics: { supply: '500,000,000', presale: 15, liquidity: 78, team: 5, marketing: 2 },
  },
  {
    id: 'quantumdex', name: 'QuantumDEX', symbol: 'QDEX', logo: '/assets/projects/quantumdex.svg',
    description: 'Next-gen decentralized exchange with MEV protection and zero-slippage swaps.',
    chain: 'eth', chainName: 'Ethereum',
    saleType: 'Presale', saleTypeKey: 'presale',
    status: 'live',
    rate: '1 ETH = 45,000 QDEX', ratePerBase: 45000,
    raised: 890000, target: 2000000, softCap: 300000, liquidity: 60,
    participants: 672,
    startsAt: now - 4 * d, endsAt: now + 5 * d + 3 * h,
    minBuy: 0.1, maxBuy: 10, kyc: false, audited: 'Hacken', refundable: false,
    aiScore: 72,
    aiBreakdown: { tokenomics: 78, contract: 88, team: 58, market: 72, liquidity: 68, community: 68 },
    aiSummary: 'Solid technical foundation with Hacken audit. Team KYC not completed — significant risk factor.',
    aiStrengths: ['Audited by Hacken', 'Clear go-to-market plan'],
    aiFlags: ['KYC not completed', 'Team identity partially unverified'],
    tokenomics: { supply: '300,000,000', presale: 30, liquidity: 55, team: 10, marketing: 5 },
  },
  {
    id: 'solana-pay', name: 'SolanaPay Pro', symbol: 'SPRO', logo: '/assets/projects/solana-pay.svg',
    description: 'Enterprise payment infrastructure on Solana. Sub-cent transactions for merchants.',
    chain: 'solana', chainName: 'Solana',
    saleType: 'Presale', saleTypeKey: 'presale',
    status: 'live',
    rate: '1 SOL = 2,800 SPRO', ratePerBase: 2800,
    raised: 680000, target: 1800000, softCap: 400000, liquidity: 65,
    participants: 413,
    startsAt: now - 5 * d, endsAt: now + 3 * d + 18 * h,
    minBuy: 1, maxBuy: 50, kyc: true, audited: 'Halborn', refundable: false,
    aiScore: 81,
    aiBreakdown: { tokenomics: 82, contract: 90, team: 78, market: 76, liquidity: 75, community: 82 },
    aiSummary: 'Solid payment protocol on Solana with Halborn audit.',
    aiStrengths: ['Halborn audit', 'KYC verified', 'Working merchant demos'],
    aiFlags: ['Competitive market'],
    tokenomics: { supply: '400,000,000', presale: 25, liquidity: 60, team: 10, marketing: 5 },
  },
  {
    id: 'base-lend', name: 'BaseLend', symbol: 'BLND', logo: '/assets/projects/base-lend.svg',
    description: 'Lending protocol native to Base with institutional yields and permissionless markets.',
    chain: 'base', chainName: 'Base',
    saleType: 'Presale', saleTypeKey: 'presale',
    status: 'upcoming',
    rate: 'TBA', ratePerBase: 0,
    raised: 0, target: 2500000, softCap: 600000, liquidity: 70,
    participants: 0,
    startsAt: now + 5 * d, endsAt: now + 15 * d,
    minBuy: 0.05, maxBuy: 8, kyc: true, audited: 'OpenZeppelin', refundable: false,
    aiScore: 85,
    aiBreakdown: { tokenomics: 86, contract: 94, team: 84, market: 80, liquidity: 84, community: 82 },
    aiSummary: 'Well-structured lending protocol on Base with OpenZeppelin audit.',
    aiStrengths: ['OpenZeppelin audit', 'Verified team', 'Clear differentiation on Base'],
    aiFlags: ['Mature competitive landscape'],
    tokenomics: { supply: '800,000,000', presale: 20, liquidity: 68, team: 8, marketing: 4 },
  },
  {
    id: 'cryptoshield', name: 'CryptoShield', symbol: 'CSHD', logo: '/assets/projects/cryptoshield.svg',
    description: 'On-chain insurance protocol for DeFi positions.',
    chain: 'bsc', chainName: 'BSC',
    saleType: 'Presale', saleTypeKey: 'presale',
    status: 'ended',
    rate: '1 BNB = 15,000 CSHD', ratePerBase: 15000,
    raised: 1500000, target: 1500000, softCap: 500000, liquidity: 70,
    participants: 892,
    startsAt: now - 10 * d, endsAt: now - 2 * d,
    minBuy: 0.05, maxBuy: 3, kyc: true, audited: 'CertiK', refundable: false,
    aiScore: 88,
    aiBreakdown: { tokenomics: 90, contract: 94, team: 85, market: 82, liquidity: 92, community: 85 },
    aiSummary: 'Successfully completed sale. Hard cap reached.',
    aiStrengths: ['Hard cap reached', 'CertiK audit', '70% liquidity locked'],
    aiFlags: [],
    tokenomics: { supply: '250,000,000', presale: 22, liquidity: 68, team: 5, marketing: 5 },
  },
];

export const POSITIONS: Position[] = [
  { id: 'zetta-chain', name: 'ZETTA CHAIN', symbol: 'ZETTA', invested: 2500, value: 4875, change: 95.0, claimable: 78125, vestingEnds: now + 60 * d },
  { id: 'metavault', name: 'MetaVault Finance', symbol: 'MVT', invested: 800, value: 1240, change: 55.0, claimable: 0, vestingEnds: now + 30 * d },
  { id: 'quantumdex', name: 'QuantumDEX', symbol: 'QDEX', invested: 1500, value: 1320, change: -12.0, claimable: 0, vestingEnds: null },
  { id: 'cryptoshield', name: 'CryptoShield', symbol: 'CSHD', invested: 600, value: 2100, change: 250.0, claimable: 15000, vestingEnds: now - d },
];

export const ACTIVITY: Activity[] = [
  { type: 'buy', project: 'ZETTA CHAIN', amount: '0.5 BNB', tokens: '62,500 ZETTA', time: now - 600000, status: 'confirmed', tx: '0xabcd1234' },
  { type: 'claim', project: 'CryptoShield', amount: '15,000 CSHD', tokens: null, time: now - 3600000, status: 'confirmed', tx: '0xef567890' },
  { type: 'stake', project: 'Z Staking — 90 days', amount: '5,000 Z', tokens: null, time: now - 5400000, status: 'confirmed', tx: '0x1234abcd' },
  { type: 'buy', project: 'MetaVault Finance', amount: '0.2 BNB', tokens: '1,700 MVT', time: now - 7200000, status: 'confirmed', tx: '0xaabbccdd' },
];

export const QUESTS: Quest[] = [
  { id: 'q1', icon: 'Zap', title: 'First Investment', desc: 'Participate in your first token sale', reward: '+500 XP · +50 Z', completed: true, progress: 100 },
  { id: 'q2', icon: 'Users', title: 'Refer 3 Friends', desc: 'Invite friends using your referral code', reward: '+800 XP · +100 Z', completed: false, progress: 33 },
  { id: 'q3', icon: 'Lock', title: 'Stake 1,000 Z', desc: 'Stake tokens in any Z staking pool', reward: '+1,000 XP · Tier Boost', completed: false, progress: 0 },
  { id: 'q4', icon: 'Vote', title: 'Vote on a Proposal', desc: 'Participate in governance', reward: '+300 XP · +30 Z', completed: false, progress: 0 },
  { id: 'q5', icon: 'Shield', title: 'Complete KYC', desc: 'Verify your identity', reward: '+1,500 XP · +200 Z', completed: false, progress: 0 },
  { id: 'q6', icon: 'TrendingUp', title: 'Reach Top 100', desc: 'Climb the leaderboard to top 100', reward: '+2,000 XP · Exclusive NFT', completed: false, progress: 15 },
];

export const PROPOSALS: Proposal[] = [
  { id: 'zip-001', title: 'Reduce platform fees for Z-staked users', category: 'Protocol', author: 'Z-PAD Core Team', status: 'active', endsAt: now + 3 * d, desc: 'Proposal to reduce platform fees by 50% for users staking 10,000+ Z tokens, incentivizing long-term ecosystem commitment.', votes: { for: 68, against: 22, abstain: 10 }, totalVotes: 2847293 },
  { id: 'zip-002', title: 'Add Solana native launchpad support', category: 'Technical', author: 'Core Dev Team', status: 'active', endsAt: now + 5 * d, desc: 'Expand Z-PAD beyond EVM chains by integrating native Solana support.', votes: { for: 82, against: 12, abstain: 6 }, totalVotes: 1923847 },
  { id: 'zip-003', title: 'Q3 Treasury Allocation: $5M for AI Vetting Engine', category: 'Treasury', author: 'Treasury Committee', status: 'active', endsAt: now + 7 * d, desc: 'Allocate $5M to accelerate ZION AI vetting engine.', votes: { for: 74, against: 18, abstain: 8 }, totalVotes: 2103472 },
  { id: 'zip-004', title: 'Enable refundable sales (DYCO) as default', category: 'Protocol', author: 'Community', status: 'passed', endsAt: now - d, desc: 'Make DYCO-style refundable sales the default for all new presales.', votes: { for: 91, against: 6, abstain: 3 }, totalVotes: 3284729 },
];

export const TICKER_ITEMS = [
  { icon: '🚀', label: 'ZETTA', value: '$0.0842', change: '+12.4%', up: true },
  { icon: '⚡', label: 'AIO', value: '$2.18', change: '+34.7%', up: true },
  { icon: '🎮', label: 'PIXV', value: '$0.024', change: '+8.1%', up: true },
  { icon: '💎', label: 'ZBRG', value: 'TBA', change: 'Starting soon', up: null },
  { icon: '🔥', label: 'MVT', value: '$0.31', change: '+5.5%', up: true },
  { icon: '⚠️', label: 'DFP', value: '$0.012', change: '-2.3%', up: false },
  { icon: '✨', label: 'SPRO', value: '$0.45', change: '+18.9%', up: true },
  { icon: '🌟', label: 'NXAI', value: 'TBA', change: 'In 3 days', up: null },
] as const;
